server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://10.10.10.70:3306/flow?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smart
    password: smart
